[package]
name = "eden-workspace-resources"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
eden-plugin-sdk.workspace = true
eden-workspace.workspace = true
serde.workspace = true
serde_yaml_ng = "0.10.0"
ignore = "0.4.33"
globset = "0.4.20"
[lints]
workspace = true
