[package]
name = "author-notes"
version = "0.1.0"
edition = "2024"
[lib]
crate-type = ["cdylib"]
path = "../../../plugins/notes/src/lib.rs"
[workspace]
[dependencies]
eden-plugin-sdk = { path = "../../../crates/eden-plugin-sdk", version = "0.1.0" }
serde = { version = "1.0.229", features = ["derive"] }
[profile.dev]
debug = 1
[profile.test]
debug = 1
