[package]
name = "author-embedded-client"
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
license = "Apache-2.0"
[workspace]
[dependencies]
eden-agent = { path = "../../../crates/eden-agent", version = "0.1.0" }
eden-plugin-sdk = { path = "../../../crates/eden-plugin-sdk", version = "0.1.0" }

[[bin]]
name = "author-embedded-client"
path = "src/main.rs"
test = false

[profile.dev.package.sha2]
opt-level = 3
