[package]
name = "eden-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
[dependencies]
eden-protocol.workspace = true
eden-kernel.workspace = true
eden-plugin-sdk.workspace = true
serde_json.workspace = true
tokio.workspace = true
[lints]
workspace = true
